### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by Dongmeng-wang** [zrmacc/RNOmni#1]
Hi,

Thanks for developing this package. I'm thinking about how this package deals with the missing values in the data. I want to keep missing values in the data but the function RankNorm() doesn't seem to work in this case. Thank you so much.

All the best,
Diana

**Comment by zrmacc** [comment]
Hi Diana, you should be able to rank-normalize the non-missing values of a vector like this:
```
x <- c(1, 2, NA, 3)
x[!is.na(x)] <- RNOmni::RankNorm(x[!is.na(x)])
```

**Comment by Dongmeng-wang** [comment]
Hi, 

Thanks for your reply. It works! Also, I used to use the code I found elsewhere to conduct inverse normalization. I'm curious if it's right. Thank you so much.
`data[, i] <- qnorm((rank(data[,i],na.last="keep")-0.5)/sum(!is.na(data[,i])))`

All the best
Diana

**Comment by Dongmeng-wang** [comment]
Hi,

I further found some variables still don't follow normal distribution after the inverse normalization. Do you think I should normalize them anyway in this case? Thank you so much for your help.

Diana

**Comment by zrmacc** [comment]
Function works as intended.
