### ISSUE TITLE
Using plink files

### ISSUE THREAD

**Issue by karpat90** [zrmacc/RNOmni#2]
Hello!

I wanted to ask if it's possible to use plink files with this package? How is the genotype matrix constructed?

Thank you!

**Comment by zrmacc** [comment]
Thanks for the question. Although reading PLINK files into R is not within the scope of this package, there are packages on CRAN for doing so, for example [genio](https://cran.r-project.org/web/packages/genio/index.html). I also have minimal code for reading in PLINK binary genotypes [here](https://github.com/zrmacc/ReadPlink).

**Comment by karpat90** [comment]
Thank you!
