### ISSUE TITLE
Extracting snps

### ISSUE THREAD

**Issue by karpat90** [zrmacc/RNOmni#3]
Hello!

Thank you for the  package. I wanted to ask if it's possible to extract SNPs for RNOmni output?

When I print out test results, there is no column with snp names
Thank you!

**Comment by zrmacc** [comment]
Thanks for your interest in the package. Can you please provide a code example?

**Comment by karpat90** [comment]
library(dplyr)
library(batch)
library(genio)
library(RNOmni)
library(ReadPlink)
library(BEDMatrix)
Here is the code:


parseCommandArgs(evaluate=TRUE)
#ids=read.delim(ids, header=FALSE, quote="")
#snps=read.delim(snps, header=FALSE, quote="")
file=sub('\\.bed$', '', bed.file)
#G=read_plink(file)
#head(G)
G=BEDMatrix(bed.file)
dim(G)
#G=G[1:1081, 1:5]
#G=readbed(bed=bed.file, obs=n, snp=snps$V1)
#G=ReadGeno("EIRA-only-updateSexPheno-rs.acpa.neg.euro")
pheno=read.table(pheno,header=TRUE,
                         stringsAsFactors = FALSE)
ids=read.delim(ids, header=FALSE, quote="")
colnames(ids)[1]="IID"

pheno=pheno[pheno$FID %in% ids$IID,]
ids=ids[ids$IID %in% pheno$FID,]
pheno$AgeOnset=as.numeric(as.character(pheno$AgeOnset))
pheno=pheno[complete.cases(pheno),]
nrow(pheno)

#pheno=pheno %>% mutate_at(c("Sex","AgeOnset","PC1","PC2","PC3","PC4","PC5"), as.character)
#pheno=pheno %>% mutate_at(c("Sex","AgeOnset","PC1","PC2","PC3","PC4","PC5"), as.numeric)


pheno=pheno %>%
select(FID,AgeOnset,Sex,PC1,PC2)
pheno$FID=pheno$FID[match(ids$IID, pheno$FID)]

head(pheno$FID)
pheno$FID=1
y=pheno$AgeOnset
pheno$AgeOnset=NULL
#names(y)=NULL
##y=as.matrix(y)
names(pheno)=NULL
pheno=data.matrix(pheno)

iint <- IINT(y = y, G = G, X = pheno)
dint <- DINT(y = y, G = G, X = pheno)
oint <- OINT(y = y, G = G, X = pheno)
write.table(oint, file=out.file, col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(dint, file=out.file2, col.names=TRUE, row.names=FALSE, quote=FALSE)
write.table(iint, file=out.file3, col.names=TRUE, row.names=FALSE, quote=FALSE)

**Comment by zrmacc** [comment]
Sorry, I do not have access to the files you have locally. Could you provide a self-contained example (e.g. something I would be able to run)?

**Comment by karpat90** [comment]
Hello!
I generated an example:

library(RNOmni)
set.seed(100)
# Design matrix
X <- cbind(1, stats::rnorm(1e3))
# Genotypes
G <- replicate(1e3, stats::rbinom(n = 1e3, size = 2, prob = 0.25))
storage.mode(G) <- "numeric"
# Phenotype
y <- exp(as.numeric(X %*% c(1, 1)) + stats::rnorm(1e3))
# Association test
p <- DINT(y = y, G = G, X = X)
head(p)
Score       SE          Z          P
1 -33.969400 23.95871 -1.4178308 0.15624018
2 -33.930264 25.15529 -1.3488324 0.17739081
3  13.697113 24.57938  0.5572603 0.57734961
4   7.705862 25.30653  0.3045009 0.76074627
5 -45.268236 25.28404 -1.7903879 0.07339158
6  49.636893 24.62293  2.0158806 0.04381246

As you can see there is no rsid in the test ouput

**Comment by karpat90** [comment]
It's also unclear for which alleles the test calculates the scores

**Comment by zrmacc** [comment]
In the example taken from the [function header](https://github.com/zrmacc/RNOmni/blob/master/R/DINT.R#L31), there were no names assigned to the columns of the genotype matrix. If the genotype columns have names assigned, as in the following example, they will appear as the row names of the output matrix:
```
set.seed(100)
n <- 10
G <- replicate(2, stats::rbinom(n = n, size = 2, prob = 0.25))
colnames(G) <- c("rs1", "rs2")
storage.mode(G) <- "numeric"
y <- stats::rnorm(n)
p <- DINT(y = y, G = G)
show(p)
```

```
        Score       SE         Z         P
rs1 -1.131595 1.008928 -1.121581 0.2620406
rs2  1.749306 1.681547  1.040296 0.2982025
```

**Comment by zrmacc** [comment]
> It's also unclear for which alleles the test calculates the scores

A score is calculated for each column of the genotype matrix. It is left to the user to encode the genotype matrix as suits their analysis (additive, dominant, recessive). In the example above the genotypes are additively coded (i.e. G in {0, 1, 2}).

**Comment by karpat90** [comment]
Thank you for your detailed response!
