### ISSUE TITLE
Missing values in the ouput file

### ISSUE THREAD

**Issue by karpat90** [zrmacc/RNOmni#4]
Hello!

I wanted to ask what could be the reason for missing values in the output file. I am performing analysis on untransformed age of onset, adjusting for sex and PCs. When I include only the first 3 PC the analysis runs without errors, but when I adjust for PC1:PC5,  I get warnings and  NA in the output file. 
There are no missing values in the phenotype file. 
 rsid Score SE Z P                  
1:100018931:G:A 5.23045219969136 NA NA NA 
1:100139143:C:A -10.0404931879582 NA NA NA 
1:100154055:T:G  33.6768997367968 NA NA NA 
Thank you!

**Comment by zrmacc** [comment]
Hello, again I do not have access to your local data. If you would like my help with debugging, please include a minimal example that reproduces the problem.
